plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/alan9820/.openclaw/workspace/articles"
publishOrigin = "default"
base = "/home/alan9820/.openclaw/workspace/articles"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]